### ISSUE TITLE
Search results are too specific?

### ISSUE THREAD

**Issue by Kenneth-Schroeder** [BenjaminOddou/alfred-dashlane#2]
Hi Benjamin,
I am trying to understand how the search results are filtered when searching for a password.
I would like the same list as with `dcli p <name>`, however, the results from your workflow seem not to include items that contains <name> in their titles.

Also, I couldn't figure out yet how `query` is used in entry.py which I hoped would give me some answers.
https://github.com/BenjaminOddou/alfred-dashlane/blob/cc8983840a0bad947ff65188d8addab973e51ece/src/entry.py#L10

Best,
Kenneth

**Comment by BenjaminOddou** [comment]
Hey @Kenneth-Schroeder,

Thanks for reaching out ! The `entry.py` python script is taking 2 arguments, the `query` you mentioned is the user input (what you type after the keyword) and the second is the type of query to indicate whether the user is requesting password or otp.

the command used to trigger the `pdash` flow is :

```shell
python3 entry.py "$1" "password"
```

Then I am using the `Alfred filters results` option to filter the result. Alfred is matching the `title` property of the supplied json data that the script is delivering.

![Capture d’écran 2023-07-19 à 21 46 46](https://github.com/BenjaminOddou/alfred-dashlane/assets/85166574/0eda22ec-0b0a-4e1d-9684-3ff104d9a57c)

You can see this json cached here (if you enabled `Allow cache`): `~/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/com.benjamino.dashlane`. This json doesn't hold passwords but only internal ids in order for a second script to search the correct password through your vault (see below):

```json
{
    "info": {
        "incognito_mode": true
    },
    "items": [
       {
            "title": "Alfred",
            "subtitle": "my\u2022\u2022\u2022\u2022r@mail.com \u01c0 Press \u23ce to copy password",
            "arg": "_password\t{0BE67C4F-F448-4FB7-B06E-DD6F15654328}",
            "icon": {
                "path": "~/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/com.benjamino.dashlane/alfredforum.com.png"
            },
            "mods": {
                "cmd": {
                    "subtitle": "my\u2022\u2022\u2022\u2022r@mail.com \u01c0 Press \u23ce to copy login",
                    "arg": "_login\tmysuper@mail.com"
                },
                "alt": {
                    "subtitle": "alfredforum.com \u01c0 Press \u23ce to open url",
                    "arg": "_url\thttps://alfredforum.com"
                }
            }
        }
    ]
}
```

Back in the `v1.0.0` I was using this function to filter results:

```python
# Filter the items based on the query
filtered_items = [item for item in items if query.lower() in item['title'].lower() or query.lower() in item['subtitle'].lower()]
```

This allowed me to search elements based on title and subtitle but it was significantly slower as each character typed by the user was reloading the full script to create a new json. That's why I opted for the `Alfred filters results` that only call the python script once and then filter the json data.

To respond to your initial demand, the search results can differ from the `dcli p <name>` in some situation when the `title` property of password element doesn't exists.

```python
    # if the url is not empty
    if v_url != '':
        domain = extract_domain(v_url)
        title = v_title if v_title else domain # title is title if exists else it should be the extracted domain
    else:
        domain = 'No URL'
        title = v_title if v_title else 'No title'  # title is title if exists else it should be 'No title' as there is no url
```

If your results aren't included in the alfred response when typing the same input as in `dcli p <name>`, could you check the title property by typing `dcli p <name> -o json` ? You can check the cached json as well.

**Comment by Kenneth-Schroeder** [comment]
Hi Benjamin,
thanks to your response, I was able to boil down the issue quickly.
I had an item with a title in the form of `... (time .... )`.
When I searched for `time` the item wasn't picked up. Alfred expected me to search for the full "word" `(time`.

I resolved this by changing the match mode under "Alfred filters results" to "Word matching - Any order".
Works great now.

Thanks again, cool project :)
